### ISSUE TITLE
PONG rom

### ISSUE THREAD

**Issue by jakears93** [wernsey/chip8#3]
The right side player's score does not increment when they get a point.  I've tested the game on another emulator to verify that the problem does not lie in the rom itself.

**Comment by wernsey** [comment]
Hi, which ROM are you referring to? Can you attach a file so that I can take a look?
Thanks

**Comment by jakears93** [comment]
Attached is the ROM I was referring to.  I had the same problem in my emulator and I found the problem was within my implementation of the opcode 0xFx65 where I was only loading contents from memory Location I+x to V[0]-V[x-1] opposed to V[x].  I'm not sure if the issue is the same for you though.
[PONG.zip](https://github.com/wernsey/chip8/files/4556154/PONG.zip)

**Comment by wernsey** [comment]
I've disassembled the ROM and then annotated it so that I can see how the program works.

The annotated disassembly is attached here:
[PONG.asm.zip](https://github.com/wernsey/chip8/files/4872803/PONG.asm.zip)

I then ran the ROM on my emulator with the built-in debugger. It seems the problem is in my implementation of the Fx33 instruction that does not properly break the score down into its BCD digits

**Comment by wernsey** [comment]
@jakears93 It turns out it was my implementation of the Fx65 that did the same thing, copying one too few bytes. I will upload a fix shortly

**Comment by wernsey** [comment]
I pushed my fix
