### ISSUE TITLE
Assembler not assembling correctly

### ISSUE THREAD

**Issue by TheShoutingParrot** [wernsey/chip8#4]
I was testing this software out (the emulator, assembler and disassembler) and everything worked perfectly fine 
until I tried to assemble a very simple program that I made which didn't work on other emulators but it did work on this emulator. I looked into it and I think I found the reason why on some emulators the assembled program doesn't work. 

Well let's take a look at the program with which I noticed this issue:

```
start:
        cls
        ld V0, #0
        ld V1, #1
        ld V2, #2
        ld V3, #3
        ld V4, #4
        ld V5, #5
        ld V6, #5
        ld V7, #7
        ld V8, #8
        ld V9, #9
        ld VA, #a
        ld VB, #b
        ld VC, #c
        ld VD, #d
        ld VE, #e
        JP start
```

This program should work right? Well it does on this emulator but not on many others. Lets take a look at the assembled a.ch8 file that the assembler produces:

```
00000000  00 e0 60 00 61 01 62 02  63 03 64 04 65 05 66 05
00000010  67 07 68 08 69 09 6a 0a  6b 0b 6c 0c 6d 0d 6e 0e
00000020  12
```

(hexdump -C a.ch8 should produce the same result)

The last byte is 0x12 and as we know the opcode 1nnn is the jump (JP) opcode but on this executable it is never "completed" i.e. it's not 1200 it is 12 which is why some emulators/interpreters may interpret this as an unknown opcode or something like that.

Now to prove that that is the case I modified the original test program by adding these 2 lines:
```
JP start
offset #201
```
This means that the program doesn't start at 200 but 201, doing this caused the hexdump of the a.ch8 file to be this:
```
00000000  12 01 e0 60 00 61 01 62  02 63 03 64 04 65 05 66
00000010  05 67 07 68 08 69 09 6a  0a 6b 0b 6c 0c 6d 0d 6e 
00000020  0e 12 01              
```

Now as we can see at the end the program jumps to 0x201 where as previously it jumped to the address 0x2
And now this program works on all emulators.

Is this a bug or is this something that has been implemented on purpose?

**Comment by wernsey** [comment]
Hi, thanks for the detailed analysis. This definitely seems like a bug. I will look into it.

**Comment by wernsey** [comment]
I know what causes the issue: It is because the very last byte of the assembled program is 0.

When the assembled program is saved, `c8_save_file()` calls `c8_prog_size()` to determine the size of the generated program

```
uint16_t c8_prog_size() {
	uint16_t n;
	for(n = TOTAL_RAM - 1; n > PROG_OFFSET && RAM[n] == 0; n--);
	return n;
}
```

So it runs backwards from the end of RAM, and looks for the first non-zero byte (which would be the last non-zero byte in the RAM).

This does not causes problems in my emulator and disassembler, because the `RAM` is zeroed out in `c8_reset()`, so the byte that's not written will be zero when the program is read.

There are a couple of things I can do: 

1. The obvious solution is that the assembler itself should track how many bytes there are in the generated program, but this would require some additional global state.
    * So say a global variable called `program_size` that is incremented when the program is assembled
    * You'd also need to set this variable when `c8_load_file` reads the binary file.
    * Anything that writes to the `RAM` externally (for example, a debugger that allows you to change the contents of `RAM`) will also need to update `program_size`.
1. I could make sure that `c8_prog_size()` always returns a multiple of 2.
1. Alternatively I could write the entire contents of the `RAM` variable to the file. I don't like it because the whole purpose of using `c8_prog_size()` is to  files would end up somewhat larger than they need to be.
1. I can also leave it unchanged and assume that an emulator running the assembled program will zero out its RAM. 

I'm leaning towards the second solution, but I'll give it some thought.

**Comment by wernsey** [comment]
I pushed a change that so that `c8_prog_size()` will always return an even number. If it computes an odd number it will assume that there is an instruction at the end of the file with an operand of 0x00 and add 1 to its return value.

It seems I got tripped up by something related when I initially wrote the code, and then _fixed_ it in the wrong way.
